_format_version: '2.1'

services:
  - name: user-service
    url: http://user-service:3000

  - name: order-service
    url: http://order-service:3001

routes:
  - name: user-route
    paths:
      - /users/*
    service: user-service

  - name: order-route
    paths:
      - /orders/*
    service: order-service
